/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "xmms"
#define VERSION "0.0.1"
#define HAVE_CFPREFERENCESCOPYAPPVALUE 1
#define HAVE_CFLOCALECOPYPREFERREDLANGUAGES 1
#define HAVE_ICONV 1
#define DEV_DSP "/dev/dsp"
#define DEV_MIXER "/dev/mixer"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define XF86VIDMODE 1
#define HAVE_LIBZ /**/
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_FNMATCH_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SCHED_H 1
#define HAVE_WCHAR_H 1
#define HAVE_FTS_H 1
#define HAVE_CODESET /**/
#define SIZEOF_LONG 0
#define SYMBOL_PREFIX "_"
